# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    # volumes:
    #   - addressbook-db:/var/lib/postgresql/data

  users-service:
    build:
      context: ./users-service
    environment:
      DB_SCHEMA: postgres
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      APP_PORT: 3000
    depends_on:
      - postgres
    ports:
      - '3001:3000'

# volumes:
#   addressbook-db:
