version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  users-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"
    # volumes:
    #   - ./:/usr/src/app/
    #   - /usr/src/app/node_modules
    environment:
      - DB_SCHEMA=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - APP_PORT=3000
      - HOST_NAME=0.0.0.0
      - DATABASE_URL=postgres://admin:password@postgres:5432/postgres
